-- Migration: pgvector extension + ai_embeddings vector column + HNSW index
--
-- IMPORTANT: This migration is hand-written, not generated by drizzle-kit.
-- Run this BEFORE running `drizzle-kit push` for the next AI tables migration.
--
-- Requirements: Supabase Pro tier (pgvector available on free + pro)
-- Verify: SELECT extversion FROM pg_extension WHERE extname = 'vector';

-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Note: ai_embeddings table is created by the next drizzle-generated migration.
-- AFTER that runs, execute the following to add the vector column + index:

-- ALTER TABLE ai_embeddings ADD COLUMN embedding vector(1536);
--
-- HNSW index for fast cosine similarity search (recommended for OpenAI embeddings)
-- CREATE INDEX ai_embeddings_vec_hnsw_idx
--   ON ai_embeddings
--   USING hnsw (embedding vector_cosine_ops)
--   WITH (m = 16, ef_construction = 64);
--
-- These ALTER + CREATE INDEX statements are commented out because drizzle-kit
-- runs migrations in alphabetical order. The ai_embeddings table is created in
-- 0003 (or whatever the next auto-generated migration is). To add the vector
-- column after that table exists, either:
--   1. Manually run the ALTER + CREATE INDEX in Supabase SQL editor after deploy
--   2. Add a new 0004_pgvector_column.sql migration that runs after the table exists
--
-- For sprint speed, recommend option 1 — Jerry/David runs these in Supabase
-- SQL editor after the next migration push.
